definitions:
  types.Activity:
    properties:
      activityType:
        type: string
      buyer:
        type: string
      createdAt:
        type: string
      image:
        type: string
      martketplaceProgramAddress:
        type: string
      mint:
        type: string
      name:
        type: string
      price:
        type: string
      seller:
        type: string
      signature:
        type: string
      symbol:
        type: string
    type: object
  types.ActivityRes:
    properties:
      activities:
        items:
          $ref: '#/definitions/types.Activity'
        type: array
      hasNextPage:
        type: boolean
    type: object
  types.Attribute:
    properties:
      name:
        example: Background
        type: string
      type:
        example: CATEGORY
        type: string
      values:
        example:
        - Vivid-tangerine
        items:
          type: string
        type: array
    type: object
  types.CollectedCollection:
    properties:
      estimatedValue:
        type: string
      floorPrice:
        type: string
      id:
        type: string
      image:
        type: string
      name:
        type: string
      nftsOwned:
        type: integer
    type: object
  types.Collection:
    properties:
      attributes:
        items:
          $ref: '#/definitions/types.Attribute'
        type: array
      description:
        type: string
      id:
        type: string
      image:
        type: string
      name:
        type: string
      statistics:
        $ref: '#/definitions/types.Statistics'
      symbol:
        type: string
      verifiedCollectionAddress:
        type: string
    type: object
  types.NFT:
    properties:
      description:
        type: string
      image:
        type: string
      lastSold:
        type: string
      listingPrice:
        type: string
      listingType:
        type: string
      mintAddress:
        type: string
      moonrankRank:
        type: integer
      name:
        type: string
      owner:
        type: string
      projectId:
        type: string
      sellerFeeBasisPoints:
        type: integer
      symbol:
        type: string
      tokenStandard:
        type: string
      traits:
        items:
          $ref: '#/definitions/types.Trait'
        type: array
      uri:
        type: string
    type: object
  types.NFTActivity:
    properties:
      activityType:
        type: string
      buyer:
        type: string
      createdAt:
        type: string
      martketplaceProgramAddress:
        type: string
      price:
        type: string
      seller:
        type: string
      signature:
        type: string
    type: object
  types.NFTActivityRes:
    properties:
      activities:
        items:
          $ref: '#/definitions/types.NFTActivity'
        type: array
      hasNextPage:
        type: boolean
    type: object
  types.NFTRes:
    properties:
      hasNextPage:
        type: boolean
      nfts:
        items:
          $ref: '#/definitions/types.NFT'
        type: array
    type: object
  types.Statistics:
    properties:
      floor1d:
        type: string
      holders:
        type: integer
      listed1d:
        type: string
      marketCap:
        type: number
      supply:
        type: integer
      volume30d:
        type: string
    type: object
  types.TimeSeries:
    properties:
      floorPrice:
        type: string
      holders:
        type: integer
      listed:
        type: integer
      timestamp:
        type: string
      volume:
        type: integer
    type: object
  types.TimeSeriesRes:
    properties:
      hasNextPage:
        type: boolean
      series:
        items:
          $ref: '#/definitions/types.TimeSeries'
        type: array
    type: object
  types.Trait:
    properties:
      rarity:
        type: number
      traitType:
        type: string
      value:
        type: string
    type: object
  types.Trend:
    properties:
      changeFloor1d:
        type: number
      changeFloor7d:
        type: number
      changeFloor30d:
        type: number
      changeListed1d:
        type: number
      changeListed7d:
        type: number
      changeListed30d:
        type: number
      changeVolume1d:
        type: number
      changeVolume7d:
        type: number
      changeVolume30d:
        type: number
      collection:
        $ref: '#/definitions/types.Collection'
      floor1d:
        type: string
      floor7d:
        type: string
      floor30d:
        type: string
      listed1d:
        type: string
      listed7d:
        type: string
      listed30d:
        type: string
      volume1d:
        type: string
      volume7d:
        type: string
      volume30d:
        type: string
    type: object
  types.TrendRes:
    properties:
      hasNextPage:
        type: boolean
      trends:
        items:
          $ref: '#/definitions/types.Trend'
        type: array
    type: object
  types.UserNFT:
    properties:
      collections:
        items:
          $ref: '#/definitions/types.CollectedCollection'
        type: array
      nfts:
        items:
          $ref: '#/definitions/types.NFT'
        type: array
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
paths:
  /collections/{address}:
    get:
      consumes:
      - application/json
      description: get collection detail information with the address
      parameters:
      - description: Collection Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Collection'
        "500":
          description: Internal Server Error
      summary: Get collection detail
      tags:
      - collections
  /collections/activities:
    get:
      consumes:
      - application/json
      description: get the activities with related to the collection
      parameters:
      - description: Collection address
        in: query
        name: address
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      - description: Activity types (['LISTING'])
        in: query
        name: activity_types
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ActivityRes'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get collection activities
      tags:
      - collections
  /collections/nfts:
    get:
      consumes:
      - application/json
      description: get the list of NFTs of the collection
      parameters:
      - description: Collection Address
        in: query
        name: address
        required: true
        type: string
      - description: 'NFT attributes to filter ([{''name'': ''Tattoos'', ''type'':
          ''CATEGORY'', ''values'': [''Barbwire'']}])'
        in: query
        name: attributes
        type: string
      - description: Only listed NFTs? (true|false)
        in: query
        name: listing_only
        type: string
      - description: Marketplace program address
        in: query
        name: program
        type: string
      - description: Auction house address
        in: query
        name: auction_house
        type: string
      - description: Sort By (lowest_listing_block_timestamp)
        in: query
        name: sort_by
        required: true
        type: string
      - description: Order (ASC|DESC)
        in: query
        name: order
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.NFTRes'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get collection NFTs
      tags:
      - collections
  /collections/series:
    get:
      consumes:
      - application/json
      description: get the historical stats for the collection
      parameters:
      - description: Collection address
        in: query
        name: address
        required: true
        type: string
      - description: Start timestamp
        in: query
        name: from_time
        required: true
        type: integer
      - description: End timestamp
        in: query
        name: to_time
        required: true
        type: integer
      - description: Granularity (PER_HOUR|PER_DAY)
        in: query
        name: granularity
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.TimeSeriesRes'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get collection historical data
      tags:
      - collections
  /collections/trend:
    get:
      consumes:
      - application/json
      description: get trending collections
      parameters:
      - description: Period (1d|7d|1m)
        in: query
        name: period
        required: true
        type: string
      - description: Sort by (volume)
        in: query
        name: sort_by
        required: true
        type: string
      - description: Order (ASC|DESC)
        in: query
        name: order
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.TrendRes'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get collection trends
      tags:
      - collections
  /nfts/{address}:
    get:
      consumes:
      - application/json
      description: get detail information about the NFT
      parameters:
      - description: NFT address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.NFT'
        "500":
          description: Internal Server Error
      summary: Get NFT detail
      tags:
      - nfts
  /nfts/activities:
    get:
      consumes:
      - application/json
      description: get the activities with related to the NFT
      parameters:
      - description: Collection address
        in: query
        name: address
        required: true
        type: string
      - description: Activity types (['LISTING'])
        in: query
        name: activity_types
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.NFTActivityRes'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get NFT activities
      tags:
      - nfts
  /nfts/offers:
    get:
      consumes:
      - application/json
      description: get the offers with related to the NFT
      parameters:
      - description: NFT address
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.NFTActivity'
            type: array
        "500":
          description: Internal Server Error
      summary: Get NFT offers
      tags:
      - nfts
  /users/activities:
    get:
      consumes:
      - application/json
      description: get the activities with related to the wallet
      parameters:
      - description: Wallet address
        in: query
        name: address
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      - description: Activity types (['LISTING'])
        in: query
        name: activity_types
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ActivityRes'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get user activities
      tags:
      - users
  /users/nfts:
    get:
      consumes:
      - application/json
      description: get the nfts of the wallet
      parameters:
      - description: Wallet address
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.UserNFT'
        "500":
          description: Internal Server Error
      summary: Get user NFTs
      tags:
      - users
  /users/nonce:
    get:
      consumes:
      - application/json
      description: get the temporary none for message signing
      parameters:
      - description: Wallet address
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Nonce
          schema:
            type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get nonce for message signing
      tags:
      - users
  /users/offers:
    get:
      consumes:
      - application/json
      description: get the offers with related to the wallet
      parameters:
      - description: Wallet address
        in: query
        name: address
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ActivityRes'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get user offers
      tags:
      - users
swagger: "2.0"
