name: Andromeda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.2'
      - name: Build
        run: go build -o andromeda ./app/main.go

      - name: Test
        env: 
          ENV: ${{ secrets.ENV }}
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          PROVIDER: ${{ secrets.PROVIDER }}
          API_KEY: ${{ secrets.API_KEY }}
          RPC_ENDPOINT: ${{ secrets.RPC_ENDPOINT }}
        run: |
          go clean -testcache && go test -v ./...
