name: Andromeda Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.2'
      - name: Build
        run: go build -o andromeda ./app/main.go

      - name: Test
        env: 
          ENV: ${{ secrets.ENV }}
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          PROVIDER: ${{ secrets.PROVIDER }}
          API_KEY: ${{ secrets.API_KEY }}
          RPC_ENDPOINT: ${{ secrets.RPC_ENDPOINT }}
        run: |
          go clean -testcache && go test -v ./...

      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.13
        if: ${{ github.ref == 'refs/heads/dev' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-motley-andromeda"
          usedocker: false
          heroku_email: "davidoliver5086@gmail.com"